[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lockd_in = "7j2F8utUft72PmSWakq9aX17UP96w6DHyQQgPhBp81cp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --show-log"

[test]
startup_wait = 50000